//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventManDbEntities : DbContext
    {
        public EventManDbEntities()
            : base("name=EventManDbEntities")
        {
        }
    
        // protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
         //   throw new UnintentionalCodeFirstException();
        //}
    
        public DbSet<Event> Events { get; set; }
        public DbSet<Registration> Registrations { get; set; }
        public DbSet<StakeHolder> StakeHolders { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.SetInitializer(
                new MigrateDatabaseToLatestVersion<EventManDbEntities, Migrations.Configuration>());
        }

        public DbSet<Sponsor> Sponsors { get; set; }
    }
}
