//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int EventId { get; set; }
        public int StakeHolderId { get; set; }
    }
}
