//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMan
{
    using System;
    using System.Collections.Generic;
    
    public partial class StakeHolder
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<short> Type { get; set; }
        public byte[] Pic { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
